name: Build and deploy Python app to Azure Web App - hemaleaderboard

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies from backend/
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact for deployment
        run: echo "Nothing to upload. Code will be deployed from repository."

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
<<<<<<< HEAD
          app-name: csenleaderboard  # <-- Sostituiscilo con il nome esatto del tuo App Service
          slot-name: Production
          package: ./backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
=======
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4E034D58F5214C6E89E5F15F1A834271 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7A901BDBB405461F93AFE6945785E3BB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_12C44BD0E3A74569A37231354B885177 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'csenleaderboard'
          slot-name: 'Production'
          
>>>>>>> 71e2478491e9483c9608a88891fe1e419054377b
