name: Build and deploy Python app to Azure Web App - hemaleaderboard

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies from backend/
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact for deployment
        run: echo "Nothing to upload. Code will be deployed from repository."

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: csenleaderboard  # <-- Sostituiscilo con il nome esatto del tuo App Service
          slot-name: Production
          package: ./backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
